server:
  port: 12000
  context-path: /aikafka
  tomcat:
      uri-encoding: UTF-8

spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.28.236:3306/touch6?autoReconnect=true
    username: aikafka
    password: '123456'

spring:
  data:
    mongodb:
#      uri: mongodb://aikafka:123456@120.77.172.143:27017/aikafka
      uri: mongodb://aikafka:123456@47.96.28.236:27017/aikafka

