server:
  port: 11000
  context-path: /aikafka
  tomcat:
      uri-encoding: UTF-8

spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.172.143:3306/touch6?autoReconnect=true
    username: aikafka
    password: 123456

rabbitmq:
  address: 120.77.172.143
  port: 15672
  username: admin
  password: admin123
  virtual-host: aikafka-vh
  publisher-confirms: true
  queueName: aikafka-queue
  exchange: aikafka-exchange
  routingKey: aikafka-routingKey